name: ZAP Scan

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  checks: write
  actions: write
  packages: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          token: ${{ github.token }}  # Using the built-in token can help with artifact operations.
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://testphp.vulnweb.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          artifact_name: 'zapScanResults'
          upload_artifact: 'false'  # Disable artifact upload if not needed.
