name: ZAP Baseline Scan

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write
  actions: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          token: ${{ secrets.MY_PAT }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://testphp.vulnweb.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          artifact_name: 'zap-scan-results'